[Run]
name = 'test'   # Run name
rundays = 10    # [days] run duration

[Time]
dt = 120        # [s] timestep
restday = 30    # [days] interval to save restartfile
saveday = 30    # [days] interval to save model output

[Geometry]
filename = '../input/CrossDots.nc'  # File containing geometry input

[Forcing]
option = 'tanh' # Available options: 'tanh', ....

[Options]
correctisf = false    #             Remove ice shelf grids sticking out and isolated points
slip      = 1         # [0...2]     Factor free slip: 0, no slip: 2, partial no slip: between 0 and 2
convop    = 1         # [0,1,2]     Option for convection when stratification is unstable 0: prescribe mindrho | 1: instantaneous convection | 2: restoring convection

[Directories]
results = '../results/'  # Main results directory in which rundirs are placed

[Filenames]
restartfile = ''  # Restartfile

[Initialisation]
Dinit = 10.0       # [m]         Initial uniform thickness

[Parameters]
#External forcing
utide     = 0.01      # [m/s]       RMS tidal velocity
Ti        = -25       # [degC]      Ice shelf temperature
#Physical parameters
f         = -1.37e-4  # [1/s]       Coriolis parameter
rhofw     = 1000.0     # [kg/m^3]    Density of freshwater
rho0      = 1028.0     # [kg/m^3]    Reference density of seawater 
rhoi      = 918.0      # [kg/m^3]    Density of ice
gamTfix   = false      # []          Turbulent exchange coefficient. If False: computed online
#Tuning
Cd        = 2.5e-3    # []          drag coefficient
Cdtop     = 1.1e-3    # []          Drag coefficient in Ustar
Ah        = 25        # [m^2/s]     Laplacian viscosity
Kh        = 25        # [m^2/s]     Diffusivity
entpar    = 'Gaspar'  #             Entrainment parameterisation, either 'Holland' or 'Gaspar'
mu        = 2.5       # []          Parameter in Gaspar entrainment. Gaspar: 0.5; Gladish: 2.5
maxdetr   = 0.5        # [m/s]       Cutoff detrainment rate, only effective when O(1e-3)
#Numerical parameters
minD      = 0.2        # [m]         Cutoff thickness
vcut      = 1.414     # [m/s]       Cutoff velocity U and V

[EOS]
#Parameters related to the equation of state and the freezing point
alpha = 3.733e-5  # [1/degC]    Thermal expansion coefficient
beta = 7.843e-4  # [1/psu]     Haline contraction coefficient
l1        = -5.73e-2  # [degC/psu]  freezing point salinity coefficient
l2        = 8.32e-2   # [degC]      freezing point offset
l3        = 7.61e-4   # [degC/m]    freezing point depth coefficient

[Constants]
#Physical parameters that are usually kept constant
g  = 9.81      # [m/s^2]     gravitational acceleration
L  = 3.34e5    # [J/kg]      Latent heat of fusion for ice
cp = 3.974e3   # [J/kg/degC] specific heat capacity of ocean
ci = 2009      # [J/kg/degC] specific heat capacity of ice
CG = 5.9e-4    # []          effective thermal Stanton number
Pr = 13.8      # []          Prandtl number
Sc = 2432.0     # []          Schmidt number
nu0 = 1.95e-6   # [m^2/s]     Molecular viscosity

[Numerics]
nu = 0.8        # []          Factor for Robert Asselin time filter
spy = 31536000  # [s/yr]      seconds per year

[Convection]
mindrho   = 0.005      # [kg/m^3]    Used for convop = 0 | Minimum density difference with ambient water
convtime  = 1000      # [s]         Used for convop = 2 | Restoring time scale towards ambient S and T where unstable

[Output]